# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: Cache

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/ghnexpress/traefik-cache

# A brief description of what your plugin is doing.
summary: Cache

# Medias associated to the plugin (optional)
iconPath:  .assets/icon.png

compatibility: TODO

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  memcached:
    address: memcached:11211
  hashkey:
    header:
      enable: true
      fields: Token,User-Agent
      ignoreFields: X-Request-Id,Postman-Token,Content-Length
    body:
      enable: true
    method:
      enable: true
  alert:
    telegram:
      chatId: -795576798
      token: xxx
  env: dev
  forceCache:
    enable: true
    expiredTime: 100 #second